### ISSUE TITLE
v4 support?

### ISSUE THREAD

**Issue by blastik** [tuxwerk/OTRS-SurveyExport#3]
Hi!

Thanks for this module. Do you think you can add support for the v4 any time soon?

Thanks!
David

**Comment by mck9** [comment]
We haven't discussed it, but will be happy if you provide a patch :-)

Marek.

**Comment by blastik** [comment]
What do you mean ? :)

**Comment by mck9** [comment]
Checkout https://github.com/tuxwerk/OTRS-SurveyExport
The OTRS 4 opm should show up soon on opar.perl-services.de.

mck.

**Comment by blastik** [comment]
no worries. i've made an SQL query at the end. thanks!
